#!/bin/bash
# Tom <linreg@gmx.net>

usage() {
    echo "Usage: $0 -c CLIENT_NAME [-e RSA|ELLIPTIC ] [-t DAYS]"
    echo "Issues a client certificate for CLIENT_NAME"
    echo
    echo "Options:"
    echo "    -c CLIENT_NAME  Client name (commonName) for the new cert"
    echo "    -e Algorithm to Use w/o -e RSA or with -e Elliptic (optional)"
    echo "    -t How many days to live (optional)"
    echo
    exit 2
}

# Var init
CLIENT_NAME=
DAYS=
export DATUM=`date +"%y-%m-%d_%H:%M"`

BIN_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
source ${BIN_DIR}/functions
source ${BIN_DIR}/defaults.conf

DAYS=$CA_DEFAULT_DAYS

while getopts c:e:t: FLAG; do
    case $FLAG in
        c) CLIENT_NAME=${OPTARG} 
           ;;
        e) ALGORITHM=${OPTARG}
        if [ -z "${ALGORITHM}" ]; then
               ALGORITHM="RSA"
           else
               ALGORITHM="ELLIPTIC"
           fi
     	   ;;
        t) DAYS="${OPTARG}"
           ;;        
        *) usage ;;
    esac
done

if [ "${CLIENT_NAME}" == "" ]; then
    usage
fi

SAFE_NAME=`echo $CLIENT_NAME | sed 's/\*/star/g'`
SAFE_NAME=`echo $SAFE_NAME | sed 's/[^A-Za-z0-9-]/-/g'`

echo
echo "Creating new client certificate for '${CLIENT_NAME}'"
echo "DAYS=$DAYS"
echo "ALGORITHM: $ALGORITHM"
echo

pushd ${BIN_DIR}/.. > /dev/null

echo -n "Enter passphase for signing CA key: "
read -s PASS
echo
export CA_PASS=${PASS}

# Generate the client cert openssl config
export SAN=""
export CA_USERNAME=${CLIENT_NAME}

if [ -f "private/${SAFE_NAME}.client.key" ]; then
	echo "Renew CSR with existing client key"

    #test -f "conf/${SAFE_NAME}.client.conf" && mv -v "conf/${SAFE_NAME}.client.conf" "conf/${SAFE_NAME}.client.conf.$DATUM"
    test -f "csr/${SAFE_NAME}.client.csr" && mv -v "csr/${SAFE_NAME}.client.csr"   "csr/${SAFE_NAME}.client.csr.$DATUM"
	test -f "certs/${SAFE_NAME}.client.crt" && mv -v "certs/${SAFE_NAME}.client.crt" "certs/${SAFE_NAME}.client.crt.$DATUM"

	openssl req -new -nodes \
            -config conf/${SAFE_NAME}.client.conf \
            -key private/${SAFE_NAME}.client.key \
            -out csr/${SAFE_NAME}.client.csr
else

	if [ ALGORITHM = "RSA" ]; then
		echo "Generate RSA Config"
		template "${BIN_DIR}/templates/client.tpl" "conf/${SAFE_NAME}.client.conf"

		# Create the client key and csr
		openssl req -new -nodes \
            -config "conf/${SAFE_NAME}.client.conf" \
            -keyout "private/${SAFE_NAME}.client.key" \
            -out "csr/${SAFE_NAME}.client.csr"
	else
		echo "Generate ELLIPTIC Config"
		template "${BIN_DIR}/templates/client-elliptic.tpl" "conf/${SAFE_NAME}.client.conf"

		# Create the client key
		echo "Generate ELLIPTIC Key"
	    openssl ecparam -name secp521r1 \
	            -genkey \
                -out "private/${SAFE_NAME}.client.key"

        # Create the client csr
        echo "Generate ELLIPTIC CSR"
        openssl req -new -nodes \
		        -key "private/${SAFE_NAME}.client.key" \
                -config "conf/${SAFE_NAME}.client.conf" \
                -out "csr/${SAFE_NAME}.client.csr"
	fi


	chmod 0400 "private/${SAFE_NAME}.client.key"
fi

# Create the client certificate
openssl ca -batch -notext \
           -in csr/${SAFE_NAME}.client.csr \
           -out certs/${SAFE_NAME}.client.crt \
           -extensions client_ext \
           -passin env:CA_PASS \
           -config conf/ca.conf \
           -days $DAYS

popd > /dev/null

echo
echo "Client certificate created."
echo

