#!/bin/bash
# Tom <linreg@gmx.net>

usage() {
    echo "Usage: $0 -s SERVER_NAME [-a ALT_NAME (DNS)] [-i ALT_NAME (IP's) ] [-e RSA|ELLIPTIC ] [-t DAYS]"
    echo "Issues a server certificate for SERVER_NAME"
    echo
    echo "Options:"
    echo "    -s SERVER_NAME  Server hostname (commonName) for the new cert"
    echo "    -a ALT_NAME (DNS) One (or more) subjectAltNames for the new cert (optional)"
    echo "    -i ALT_NAME (IP)  One (or more) IP subjectAltNames for the new cert (optional)"
    echo "    -e Algorithm to Use w/o -e RSA or with -e Elliptic (optional)"
    echo "    -t How many days to live (optional)"
    echo
    exit 2
}

# Var init
SERVER_NAME=
ALT_NAME=
DAYS=
export DATUM=`date +"%y-%m-%d_%H:%M"`

BIN_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
source ${BIN_DIR}/functions
source ${BIN_DIR}/defaults.conf

DAYS=$CA_DEFAULT_DAYS

while getopts s:a:i:e:t: FLAG; do
    case $FLAG in
        s) SERVER_NAME=${OPTARG}
           if [ -z "${ALT_NAME}" ]; then
               ALT_NAME="DNS:${OPTARG}"
           else
               ALT_NAME="${ALT_NAME}, DNS:${OPTARG}"
           fi
           ;;
        a) if [ -z "${ALT_NAME}" ]; then
               ALT_NAME="DNS:${OPTARG}"
           else
               ALT_NAME="${ALT_NAME}, DNS:${OPTARG}"
           fi
           ;;
        i) if [ -z "${ALT_NAME}" ]; then
               ALT_NAME="IP:${OPTARG}"
           else
               ALT_NAME="${ALT_NAME}, IP:${OPTARG}"
           fi
           ;;
        e) ALGORITHM=${OPTARG}
	        if [ -z "${ALGORITHM}" ]; then
               ALGORITHM="RSA"
           else
               ALGORITHM="ELLIPTIC"
           fi
     	   ;;
        t) DAYS="${OPTARG}"
           echo "==> DAYS=${OPTARG}"
           ;;
        *) usage
           ;;
    esac
done

if [ "${SERVER_NAME}" == "" ]; then
    usage
fi

# Sanitize the commonName to make it suitable for use in filenames
SAFE_NAME=`echo ${SERVER_NAME} | sed 's/\*/star/g'`
SAFE_NAME=`echo ${SAFE_NAME} | sed 's/[^A-Za-z0-9-]/-/g'`

echo
echo "Creating new SSL server certificate for:"
echo "commonName: ${SERVER_NAME}"
echo "subjectAltName: ${ALT_NAME}"
echo "DAYS=$DAYS"
echo

pushd ${BIN_DIR}/.. > /dev/null

echo -n "Enter passphase for signing CA key: "
read -s PASS
echo
export CA_PASS=${PASS}

# Generate the server openssl config
export CA_HOSTNAME=${SERVER_NAME}
export SAN=${ALT_NAME}

if [ -f "private/${SAFE_NAME}.server.key" ]; then
	echo "Renew CSR with existing server key"

    #test -f "conf/${SAFE_NAME}.server.conf" && mv -v "conf/${SAFE_NAME}.server.conf" "conf/${SAFE_NAME}.server.conf.$DATUM"
    test -f "csr/${SAFE_NAME}.server.csr" && mv -v "csr/${SAFE_NAME}.server.csr"   "csr/${SAFE_NAME}.server.csr.$DATUM"
	test -f "certs/${SAFE_NAME}.server.crt" && mv -v "certs/${SAFE_NAME}.server.crt" "certs/${SAFE_NAME}.server.crt.$DATUM"

	openssl req -new -nodes \
            -config conf/${SAFE_NAME}.server.conf \
            -key private/${SAFE_NAME}.server.key \
            -out csr/${SAFE_NAME}.server.csr
else

	if [ ALGORITHM = "RSA" ]; then
		echo "Generate RSA Config"
		template "${BIN_DIR}/templates/server.tpl" "conf/${SAFE_NAME}.server.conf"

		# Create the server key and csr
		openssl req -new -nodes \
            -config "conf/${SAFE_NAME}.server.conf" \
            -keyout "private/${SAFE_NAME}.server.key" \
            -out "csr/${SAFE_NAME}.server.csr"
	else
		echo "Generate ELLIPTIC Config"
		template "${BIN_DIR}/templates/server-elliptic.tpl" "conf/${SAFE_NAME}.server.conf"

		# Create the server key
		echo "Generate ELLIPTIC Key"
	    openssl ecparam -name secp521r1 \
	            -genkey \
                -out "private/${SAFE_NAME}.server.key"

        # Create the server csr
        echo "Generate ELLIPTIC CSR"
        openssl req -new -nodes \
		        -key "private/${SAFE_NAME}.server.key" \
                -config "conf/${SAFE_NAME}.server.conf" \
                -out "csr/${SAFE_NAME}.server.csr"
	fi

	chmod 0400 private/${SAFE_NAME}.server.key
fi

# Create the server certificate
openssl ca -batch -notext \
           -in csr/${SAFE_NAME}.server.csr \
           -out certs/${SAFE_NAME}.server.crt \
           -extensions server_ext \
           -passin env:CA_PASS \
           -config conf/ca.conf \
           -days $DAYS

popd > /dev/null

echo
echo "Server certificate created."
echo

